#!/bin/sh

[ -n "$DEVICE" ] || exit 0
[ "$ACTION" = ifup ] &&  {                                                                            
    echo y | /etc/SimpleHFSCgamerscript.sh
    logger -t SimpleHFSCgamerscript "Reloading SimpleHFSCgamerscript.sh due to $ACTION of $INTERFACE ($DEVICE)"
}
