#!/bin/sh

[ -n "$DEVICE" ] || exit 0
[ "$ACTION" = ifup ] &&  {                                                                            
    echo y | /etc/SimpleHFSCGamerScript.sh
    logger -t SimpleHFSCGamerScript "Reloading SimpleHFSCGamerScript.sh due to $ACTION of $INTERFACE ($DEVICE)"
}
